apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-system-config
  labels:
    app: garage-system
data:
  DB_HOST: "garage-postgresql"
  DB_PORT: "5432"
  DB_NAME: "garagesystem_db"
  DB_USER: "garage"
  MAIL_HOST: "garage-mailhog"
  MAIL_PORT: "1025"
  MAIL_FROM: "noreply@garagesystem.com"
  APP_BASE_URL: "http://localhost:8080"