apiVersion: v1
kind: Secret
metadata:
  name: garage-system-secret
  labels:
    app: garage-system
type: Opaque
data:
  DB_PASS: Z2FyYWdlMTIz                     # garage123
  JWT_SECRET: dHJvcXVlLXBvci11bWEtY2hhdmUtc2VjcmV0YS1sb25nYS1lLWFsZWF0b3JpYQ==
  ADMIN_USERNAME: YWRtaW4=                  # admin
  ADMIN_PASSWORD: YWRtaW4xMjM=              # admin123